[package]
authors = ["Const <devconst@proton.me>"]
description = "T.S.T. game data"
edition = "2021"
publish = false
version = "0.1.2"
name = "gamedata"

[lib]
path = "lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fastrand = "1.4"
# rand = "0.8.5"
